# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-29 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedirectUrl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=16)),
                (
                    "destination",
                    models.URLField(max_length=400, verbose_name="Ziel URL"),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
        )
    ]
